baseurl = "https://liga-dos-programadores.github.io/"
languageCode = "pt-br"
theme = "hello-friend"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # "light" or "dark"
  defaultTheme = "dark"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2
  # Show reading time in minutes for posts
  showReadingTime = true

[params.favicon]
  # you may want to use https://realfavicongenerator.net to generate you files
  # used in layouts/partials/head.favicon.html
  # relURL is applied to path 
  enable    = true
  path      = "/static/img/favicon/favicon.ico"
  version   = "1.0" 

[languages]
  [languages.en]
    title = "Liga dos Programadores"
    subtitle = "Blog"
    keywords = ""
    copyright = ""
    menuMore = "Mostrar mais"
    writtenBy = "Escrito por"
    readMore = "Leia mais"
    readOtherPosts = "Leia outros posts"
    newerPosts = "Posts mais novos"
    olderPosts = "Post mais antigos"
    minuteReadingTime = "minutos de leitura"
    dateFormatSingle = "02/01/2006"
    dateFormatList = "02/01/2006"


    [languages.en.params.logo]
      logoText = "Liga dos Programadores"
      logoHomeLink = ""
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "sobre"
        name = "Sobre"
        url = "/sobre"
      [[languages.en.menu.main]]
        identifier = "discord"
        name = "Discord"
        url = "/discord"